Ext.define("ExtMVC.model.socio.Socio",{
   extend:"Ext.data.Model",
   fields:[
       {
           name:"socioid",
           type:"int"
       },
       {
         name:"centralid",
         type:"int"
       },
       {
         name:"central",
         type:"string"
       },
       {
         name:"comiteid",
         type:"int"
       },
       {
         name:"codigointerno",
         type:"string"
       },
       {
           name:"apepater",
           type:"string"
       },
       {
           name:"apemater",
           type:"string"
       },
       {
           name:"nombre",
           type:"string"
       },
       {
           name:"dni",
           type:"string"
       },
       {
           name:"opcionid",
           type:"int"
       },
       {
           name:"opcion",
           type:"string"
       },
       {
           name:"sectorid",
           type:"int"
       },
       {
           name:"sector",
           type:"string"
       },
       {
           name:"grupoid",
           type:"int"
       },
       {
           name:"grupo",
           type:"string"
       },
       {
           name:"parcelaid",
           type:"int"
       },
       {
           name:"parcela",
           type:"string"
       },
       {
           name:"etapaid",
           type:"int"
       },
       {
           name:"etapa",
           type:"string"
       },
       {
           name:"barrioid",
           type:"int"
       },
       {
           name:"barrio",
           type:"string"
       },
       {
           name:"asentamientohumanoid",
           type:"int"
       },
       {
           name:"asentamientohumano",
           type:"string"
       },
       {
           name:"asociacionid",
           type:"int"
       },
       {
           name:"asociacion",
           type:"string"
       },
       {
           name:"cooperativaid",
           type:"int"
       },
       {
           name:"cooperativa",
           type:"string"
       },
       {
           name:"manzanaid",
           type:"int"
       },
       {
           name:"manzana",
           type:"string"
       },
       {
           name:"loteid",
           type:"int"
       },
       {
           name:"lote",
           type:"string"
       },
       {
           name:"referenciaid",
           type:"int"
       },
       {
           name:"referencia",
           type:"string"
       },
       {
           name:"observacion",
           type:"int"
       },
       {
           name:"observacion",
           type:"string"
       }
        
   ]
});


