Ext.define("ExtMVC.model.manzana.Manzana",{
   extend:"Ext.data.Model",
   fields:[
       {
           name:"manzanaid",
           type:"int"
       },
       {
           name:"descripcion",
           type:"string"
       }
  ]
});