Ext.define("ExtMVC.model.sector.Sector",{
   extend:"Ext.data.Model",
   fields:[
       {
           name:"sectorid",
           type:"int"
       },
       {
           name:"descripcion",
           type:"string"
       }
   ]
});