Ext.define("ExtMVC.model.coordinador.Coordinador",{
   extend:"Ext.data.Model",
   fields:[
       {
           name:"idcoor",
           type:"int"
       },
       {
           name:"nombres",
           type:"string"
       },
       {
           name:"apellidos",
           type:"string"
       },
       {
           name:"idcargo",
           type:"int"
       },
       {
          name:"cargo",
          type:"string"
       },
       {
           name:"telefono",
           type:"string"
       },
       {
           name:"estado",
           type:"int"
       }
       ,
       {
           name:"coordinador",
           type:"string"
       }
   ]
});