Ext.define("ExtMVC.model.supervisor.Supervisor",{
    extend:"Ext.data.Model",    
    fields:[
        {
            name:"idsuper",
            type:"int"
        },
        {
            name:"nombres",
            type:"string"
        },
        {
           name:"apellidos",
           type:"string"
        },
        {
           name:"telefono",
           type:"string"
        },
        {
            name:"estado",
            type:"int"
        },
        {
            name:"supervisor",
            type:"string"
        }
    ]
});